### ISSUE TITLE
Android11 Toast显示闪退

### ISSUE THREAD

**Issue by Adolphsa** [opensource-zhuzhiqiang/smart-show#40]
2020-10-26 18:30:24.821 6798-6798/com.lucas.enabot E/om.lucas.enabo: Invalid ID 0x00000000.
2020-10-26 18:30:24.822 6798-6798/com.lucas.enabot D/CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10156; state: ENABLED
2020-10-26 18:30:24.825 6798-6798/com.lucas.enabot E/Toast: getYOffset() shouldn't be called on text toasts, the result may not reflect actual values.
2020-10-26 18:30:24.825 6798-6798/com.lucas.enabot D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2020-10-26 18:30:24.826 6798-6798/com.lucas.enabot E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.lucas.enabot, PID: 6798
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
        at com.coder.zzq.smartshow.toast.OriginalToastUI.createToast(OriginalToastUI.java:31)
        at com.coder.zzq.smartshow.toast.AbstractToast.showUI(AbstractToast.java:138)
        at com.coder.zzq.smartshow.toast.PlainToast.showInCenter(PlainToast.java:50)
        at com.coder.zzq.smartshow.toast.SmartToast.showInCenter(SmartToast.java:54)
        at com.lucas.enabot.ui.page.login.SignUpActivity$ClickProxy.sendCode(SignUpActivity.java:77)
        at com.lucas.enabot.databinding.ActivitySignUpBindingImpl._internalCallbackOnClick(ActivitySignUpBindingImpl.java:684)
        at com.lucas.enabot.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by LoveYourselfAndMe** [comment]
有解决么?

**Comment by zhiqiang-series** [comment]
抱歉，迟迟没有更新，已修复，请使用3.0.4版本（临时修复版）。本周有更大的优化重构版本发布

**Comment by zhiqiang-series** [comment]
> 有解决么?

抱歉，迟迟没有更新，已修复，请使用3.0.4版本（临时修复版）。本周有更大的优化重构版本发布

**Comment by zhiqiang-series** [comment]
> 2020-10-26 18:30:24.821 6798-6798/com.lucas.enabot E/om.lucas.enabo: Invalid ID 0x00000000.
> 2020-10-26 18:30:24.822 6798-6798/com.lucas.enabot D/CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10156; state: ENABLED
> 2020-10-26 18:30:24.825 6798-6798/com.lucas.enabot E/Toast: getYOffset() shouldn't be called on text toasts, the result may not reflect actual values.
> 2020-10-26 18:30:24.825 6798-6798/com.lucas.enabot D/AndroidRuntime: Shutting down VM
> 
> ```
> --------- beginning of crash
> ```
> 
> 2020-10-26 18:30:24.826 6798-6798/com.lucas.enabot E/AndroidRuntime: FATAL EXCEPTION: main
> Process: com.lucas.enabot, PID: 6798
> java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
> at com.coder.zzq.smartshow.toast.OriginalToastUI.createToast(OriginalToastUI.java:31)
> at com.coder.zzq.smartshow.toast.AbstractToast.showUI(AbstractToast.java:138)
> at com.coder.zzq.smartshow.toast.PlainToast.showInCenter(PlainToast.java:50)
> at com.coder.zzq.smartshow.toast.SmartToast.showInCenter(SmartToast.java:54)
> at com.lucas.enabot.ui.page.login.SignUpActivity$ClickProxy.sendCode(SignUpActivity.java:77)
> at com.lucas.enabot.databinding.ActivitySignUpBindingImpl._internalCallbackOnClick(ActivitySignUpBindingImpl.java:684)
> at com.lucas.enabot.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
> at android.view.View.performClick(View.java:7448)
> at android.view.View.performClickInternal(View.java:7425)
> at android.view.View.access$3600(View.java:810)
> at android.view.View$PerformClick.run(View.java:28305)
> at android.os.Handler.handleCallback(Handler.java:938)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loop(Looper.java:223)
> at android.app.ActivityThread.main(ActivityThread.java:7656)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

抱歉，迟迟没有更新，已修复，请使用3.0.4版本（临时修复版）。本周有更大的优化重构版本发布

**Comment by zhiqiang-series** [comment]
implementation ('com.github.zhiqiang-series.smart-show:toast:3.0.4')

**Comment by zhiqiang-series** [comment]
你好，android11已完美适配，请使用最新版本3.1.3

**Comment by zhiqiang-series** [comment]
> 有解决么?

已解决
